services:
  postgres:
    container_name: employee_recruiter
    image: postgres:17.5
    environment:
      POSTGRES_USER: albert
      POSTGRES_PASSWORD: albert
      PGDATA: /data/postgres
      POSTGRES_DB: employee_recruiter_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres: